name: API Test Otv 5

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: OTV.postman_collection.json
      - name: Notify
        if: ${{ success() }}
        run: |
          curl --location 'https://trigger.esp8266-server.de/api/?id=2859&hash=c0abcd10598f95c63b08571cb9b54a15'
