name: API Test Otv

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: ZTC.postman_collection.json
          envVar: '[{ "key": "slackUrl", "value": "${{ secrets.SLACK_URL }}" }]'
      - name: Notify
        if: ${{ success() }}
        run: |
          curl --location 'https://trigger.esp8266-server.de/api/?id=2859&hash=c0abcd10598f95c63b08571cb9b54a15'
          curl -X POST -H 'Content-type: application/json' --data '{"text":"TEST ZTC IS LIVE go to https://www.zewa.net/de/gewinnspiele/gratis-testen/"}' ${{ secrets.SLACK_URL }}
